In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('turnstile_160917.csv')
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,5817505,1971936
1,A002,R051,02-00-00,59 ST,NQR456,BMT,09/10/2016,04:00:00,REGULAR,5817544,1971940
2,A002,R051,02-00-00,59 ST,NQR456,BMT,09/10/2016,08:00:00,REGULAR,5817564,1971981
3,A002,R051,02-00-00,59 ST,NQR456,BMT,09/10/2016,12:00:00,REGULAR,5817678,1972094
4,A002,R051,02-00-00,59 ST,NQR456,BMT,09/10/2016,16:00:00,REGULAR,5817925,1972180

In [8]:
df.rename(columns = {'C/A' : 'CA'}, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 192878 entries, 0 to 192877
Data columns (total 11 columns):
C/A                                                                     192878 non-null object
UNIT                                                                    192878 non-null object
SCP                                                                     192878 non-null object
STATION                                                                 192878 non-null object
LINENAME                                                                192878 non-null object
DIVISION                                                                192878 non-null object
DATE                                                                    192878 non-null object
TIME                                                                    192878 non-null object
DESC                                                                    192878 non-null object
ENTRIES                                                                 192878 non-null int64
EXITS                                                                   192878 non-null int64
dtypes: int64(2), object(9)
memory usage: 17.7+ MB

In [10]:
df['CA'].unique()

array(['A002', 'A006', 'A007', 'A010', 'A011', 'A013', 'A014', 'A015',
       'A016', 'A021', 'A022', 'A025', 'A027', 'A029', 'A030', 'A031',
       'A033', 'A034', 'A035', 'A037', 'A038', 'A039', 'A041', 'A042',
       'A043', 'A046', 'A047', 'A049', 'A050', 'A054', 'A055', 'A058',
       'A060', 'A061', 'A064', 'A066', 'A069', 'A071', 'A077', 'A081',
       'A082', 'A083', 'A084', 'A085', 'B004', 'B009', 'B010', 'B012',
       'B013', 'B014', 'B015', 'B016', 'B017', 'B018', 'B019', 'B020',
       'B021', 'B022', 'B023', 'B024', 'B024A', 'B025', 'B026', 'B027',
       'B028', 'B029', 'B031', 'B032', 'B034', 'C001', 'C003', 'C004',
       'C008', 'C009', 'C010', 'C011', 'C012', 'C014', 'C015', 'C016',
       'C017', 'C018', 'C019', 'C020', 'C021', 'C022', 'C023', 'C024',
       'C025', 'C026', 'C027', 'C028', 'D002', 'D003', 'D005', 'D008',
       'D009', 'D010', 'D012', 'D015', 'D016', 'E001', 'E003', 'E004',
       'E005', 'E009', 'E011', 'E012', 'E013', 'E014', 'E015', 'E016',
       'G001', 'G009', 'G011', 'G015', 'H001', 'H003', 'H005', 'H006',
       'H007', 'H008', 'H009', 'H012', 'H013', 'H014', 'H015', 'H016',
       'H017', 'H019', 'H022', 'H023', 'H026', 'H027', 'H028', 'H030',
       'H032', 'H033', 'H035', 'H037', 'H038', 'H039', 'H040', 'H041',
       'JFK01', 'JFK02', 'JFK03', 'J001', 'J002', 'J003', 'J005', 'J007',
       'J009', 'J012', 'J013', 'J016', 'J017', 'J020', 'J021', 'J022',
       'J023', 'J024', 'J025', 'J028', 'J030', 'J031', 'J032', 'J034',
       'J035', 'J037', 'K017', 'K019', 'K022', 'K024', 'K025', 'K026',
       'N001', 'N002A', 'N003', 'N006A', 'N007A', 'N009', 'N010', 'N011',
       'N012', 'N013', 'N016A', 'N017', 'N019', 'N020', 'N022', 'N023',
       'N024', 'N025', 'N026', 'N029', 'N030', 'N034', 'N035', 'N037',
       'N039', 'N040', 'N043', 'N044', 'N045', 'N046', 'N049', 'N051',
       'N056', 'N057', 'N060', 'N062', 'N062A', 'N063', 'N063A', 'N067',
       'N068', 'N069', 'N070', 'N071', 'N072', 'N073', 'N075', 'N076',
       'N077', 'N078', 'N080', 'N083', 'N086', 'N087', 'N089', 'N090',
       'N091', 'N092', 'N094', 'N095', 'N095A', 'N098', 'N100', 'N101',
       'N102', 'N103', 'N108', 'N110', 'N111', 'N112A', 'N113', 'N114',
       'N116', 'N117', 'N118', 'N119', 'N120', 'N120A', 'N121B', 'N122',
       'N123B', 'N124', 'N125', 'N126', 'N127', 'N128', 'N129', 'N130',
       'N131', 'N133', 'N134', 'N135', 'N137', 'N138', 'N139', 'N141',
       'N181', 'N181A', 'N182', 'N183', 'N184', 'N185', 'N186', 'N187',
       'N191', 'N192', 'N193', 'N194', 'N195', 'N196', 'N202', 'N203',
       'N205', 'N206', 'N207', 'N208', 'N209', 'N210', 'N212', 'N213',
       'N215', 'N217', 'N218', 'N220', 'N221', 'N222', 'N223', 'N224',
       'N225', 'N300', 'N301', 'N303', 'N304', 'N305', 'N305A', 'N306',
       'N307', 'N309A', 'N310', 'N311', 'N312', 'N314', 'N315', 'N316',
       'N316A', 'N317', 'N318', 'N319', 'N322', 'N323', 'N324', 'N325A',
       'N327', 'N329', 'N329A', 'N330', 'N330C', 'N331', 'N332', 'N333',
       'N333A', 'N333B', 'N334B', 'N335', 'N336', 'N337', 'N338', 'N338B',
       'N339', 'N339A', 'N340', 'N340A', 'N342', 'N343', 'N400A', 'N401',
       'N405', 'N408A', 'N409', 'N412', 'N414', 'N414A', 'N415', 'N416',
       'N417', 'N418', 'N419', 'N420B', 'N422', 'N500', 'N501', 'N501A',
       'N502', 'N503', 'N504', 'N505', 'N506', 'N507', 'N508', 'N509',
       'N510', 'N511', 'N512', 'N513', 'N519', 'N519A', 'N520', 'N521',
       'N523', 'N525', 'N526', 'N528', 'N529', 'N530', 'N531', 'N532',
       'N533', 'N534', 'N535', 'N536', 'N537', 'N539A', 'N541', 'N542',
       'N543', 'N544', 'N545', 'N546', 'N547', 'N548', 'N549', 'N550',
       'N551', 'N553', 'N554', 'N555', 'N556', 'N557', 'N558', 'N559',
       'N561', 'N562', 'N600', 'N601', 'N602', 'N603', 'N604', 'N605',
       'N606', 'N607', 'OB01', 'PTH01', 'PTH02', 'PTH03', 'PTH04', 'PTH05',
       'PTH06', 'PTH07', 'PTH09', 'PTH10', 'PTH11', 'PTH12', 'PTH13',
       'PTH16', 'PTH17', 'PTH18', 'PTH19', 'PTH20', 'PTH22', 'R101',
       'R102', 'R103', 'R110', 'R111', 'R112', 'R112A', 'R113', 'R114',
       'R115', 'R116', 'R117', 'R118', 'R119', 'R120', 'R121', 'R122',
       'R123', 'R124', 'R125', 'R126', 'R127', 'R128', 'R129', 'R130',
       'R131', 'R132', 'R133', 'R134', 'R135', 'R137', 'R138', 'R139',
       'R141', 'R142', 'R143', 'R145', 'R147', 'R148', 'R151', 'R154',
       'R155', 'R158', 'R159', 'R160', 'R160A', 'R161A', 'R161B', 'R162',
       'R163', 'R164', 'R165', 'R166', 'R168A', 'R169', 'R170', 'R171',
       'R172', 'R173', 'R174', 'R175', 'R176', 'R177', 'R178', 'R179',
       'R180', 'R182', 'R183', 'R185', 'R186', 'R188', 'R190', 'R192',
       'R194', 'R196', 'R197', 'R200A', 'R201', 'R202', 'R203', 'R203A',
       'R204', 'R204A', 'R205A', 'R206', 'R208', 'R210', 'R210A', 'R215',
       'R216', 'R217A', 'R219', 'R220', 'R221', 'R226', 'R226A', 'R227',
       'R227A', 'R228', 'R229', 'R230', 'R231', 'R231A', 'R232', 'R232A',
       'R236', 'R237', 'R237B', 'R238', 'R238A', 'R240', 'R241A', 'R242',
       'R242A', 'R243', 'R244', 'R244A', 'R245', 'R245A', 'R246', 'R247',
       'R248', 'R249', 'R250', 'R251', 'R252', 'R253', 'R254', 'R256',
       'R257', 'R258', 'R259', 'R260', 'R261', 'R262', 'R262A', 'R262B',
       'R283', 'R284', 'R285', 'R286', 'R287', 'R288', 'R289', 'R290',
       'R291', 'R293', 'R294', 'R301', 'R302', 'R303', 'R304', 'R305',
       'R306', 'R307', 'R308', 'R309', 'R310', 'R311', 'R312', 'R314',
       'R315', 'R316', 'R317', 'R318', 'R319', 'R320', 'R321', 'R322',
       'R323', 'R325', 'R326', 'R327', 'R328', 'R329', 'R330', 'R331',
       'R332', 'R333', 'R334', 'R335', 'R336', 'R401', 'R402', 'R403',
       'R404', 'R405', 'R406', 'R407', 'R408', 'R409', 'R410', 'R411',
       'R412', 'R413', 'R414', 'R415', 'R416', 'R417', 'R418', 'R419',
       'R420', 'R421', 'R422', 'R423', 'R501', 'R503', 'R504', 'R506',
       'R507', 'R508', 'R509', 'R510', 'R511', 'R512', 'R513', 'R514',
       'R515', 'R516', 'R517', 'R518', 'R519', 'R520', 'R521', 'R523',
       'R524', 'R525', 'R526', 'R527', 'R528', 'R529', 'R530', 'R532',
       'R532H', 'R533', 'R534', 'R550', 'R600', 'R601A', 'R602', 'R604',
       'R605', 'R606', 'R608', 'R609', 'R610', 'R612', 'R617', 'R618',
       'R619', 'R621', 'R622', 'R623', 'R624', 'R625', 'R626', 'R627',
       'R628', 'R629', 'R630', 'R632', 'R633', 'R634', 'R635', 'R636',
       'R637', 'R639', 'R641', 'R643', 'R644', 'R645', 'R646', 'R647',
       'R726', 'R727', 'R728', 'R729', 'R730', 'S101', 'S101A', 'S102',
       'TRAM1', 'TRAM2'], dtype=object)

In [6]:
df.STATION.unique()

array(['59 ST', '5 AV/59 ST', '57 ST-7 AV', '49 ST', 'TIMES SQ-42 ST',
       '34 ST-HERALD SQ', '28 ST', '23 ST', '14 ST-UNION SQ', '8 ST-NYU',
       'PRINCE ST', 'CANAL ST', 'CITY HALL', 'CORTLANDT ST', 'RECTOR ST',
       'WHITEHALL S-FRY', 'DELANCEY/ESSEX', 'BOWERY', 'CHAMBERS ST',
       'FULTON ST', 'BROAD ST', '7 AV', 'PARK PLACE', 'BOTANIC GARDEN',
       'PROSPECT PARK', 'PARKSIDE AV', 'CHURCH AV', 'BEVERLEY ROAD',
       'CORTELYOU RD', 'NEWKIRK PLAZA', 'AVENUE H', 'AVENUE J', 'AVENUE M',
       'KINGS HWY', 'AVENUE U', 'NECK RD', 'SHEEPSHEAD BAY',
       'BRIGHTON BEACH', 'OCEAN PKWY', 'BOROUGH HALL', 'JAY ST-METROTEC',
       'DEKALB AV', 'ATL AV-BARCLAY', 'UNION ST', '4AV-9 ST',
       'PROSPECT AV', '25 ST', '36 ST', '45 ST', '53 ST', 'BAY RIDGE AV',
       '77 ST', '86 ST', 'BAY RIDGE-95 ST', '8 AV', 'FT HAMILTON PKY',
       'NEW UTRECHT AV', '18 AV', '20 AV', 'BAY PKWY', '9 AV', '50 ST',
       '55 ST', '71 ST', '79 ST', '25 AV', 'BAY 50 ST', 'CONEY IS-STILLW',
       'W 8 ST-AQUARIUM', '6 AV', '3 AV', '1 AV', 'BEDFORD AV',
       'LORIMER ST', 'GRAHAM AV', 'GRAND ST', 'MONTROSE AV', 'MORGAN AV',
       'JEFFERSON ST', 'MYRTLE-WYCKOFF', 'HALSEY ST', 'WILSON AV',
       'BUSHWICK AV', 'ATLANTIC AV', 'SUTTER AV', 'LIVONIA AV', 'NEW LOTS',
       'EAST 105 ST', 'CANARSIE-ROCKAW', 'HOWARD BCH JFK',
       'JFK JAMAICA CT1', 'MARCY AV', 'HEWES ST', 'FLUSHING AV',
       'MYRTLE AV', 'KOSCIUSZKO ST', 'GATES AV', 'CHAUNCEY ST',
       'ALABAMA AV', 'VAN SICLEN AV', 'CLEVELAND ST', 'NORWOOD AV',
       'CRESCENT ST', 'CYPRESS HILLS', '75 ST-ELDERTS', '85 ST-FOREST PK',
       'WOODHAVEN BLVD', '104 ST', '111 ST', '121 ST', 'CENTRAL AV',
       'KNICKERBOCKER', 'SENECA AVE', 'FOREST AVE', 'FRESH POND RD',
       'METROPOLITAN AV', 'INWOOD-207 ST', 'DYCKMAN ST', '190 ST',
       '181 ST', '175 ST', '168 ST', '163 ST-AMSTERDM', '155 ST', '145 ST',
       '135 ST', '125 ST', '116 ST', 'CATHEDRAL PKWY', '103 ST', '96 ST',
       '81 ST-MUSEUM', '72 ST', '59 ST COLUMBUS', '42 ST-PORT AUTH',
       '34 ST-PENN STA', '14 ST', 'W 4 ST-WASH SQ', 'SPRING ST',
       'WORLD TRADE CTR', 'HIGH ST', 'HOYT-SCHER', 'LAFAYETTE AV',
       'CLINTON-WASH AV', 'FRANKLIN AV', 'NOSTRAND AV', 'KINGSTON-THROOP',
       'UTICA AV', 'RALPH AV', 'ROCKAWAY AV', 'BROADWAY JCT', 'LIBERTY AV',
       'VAN SICLEN AVE', 'SHEPHERD AV', 'EUCLID AV', 'GRANT AV', '80 ST',
       '88 ST', 'ROCKAWAY BLVD', 'OZONE PK LEFFRT', 'AQUEDUCT N.COND',
       'AQUEDUCT RACETR', 'BROAD CHANNEL', 'BEACH 90 ST', 'BEACH 98 ST',
       'BEACH 105 ST', 'ROCKAWAY PARK B', 'BEACH 67 ST', 'BEACH 60 ST',
       'BEACH 44 ST', 'BEACH 36 ST', 'BEACH 25 ST', 'FAR ROCKAWAY',
       '161/YANKEE STAD', '167 ST', '170 ST', '174-175 STS', 'TREMONT AV',
       '182-183 STS', 'FORDHAM RD', 'KINGSBRIDGE RD', 'BEDFORD PK BLVD',
       'NORWOOD 205 ST', '5 AV/53 ST', 'LEXINGTON AV/53', 'COURT SQ-23 ST',
       'QUEENS PLAZA', 'STEINWAY ST', '46 ST', 'NORTHERN BLVD', '65 ST',
       'JKSN HT-ROOSVLT', 'ELMHURST AV', 'GRAND-NEWTOWN',
       '63 DR-REGO PARK', '67 AV', 'FOREST HILLS 71', '75 AV',
       'KEW GARDENS', 'BRIARWOOD', 'SUTPHIN BLVD', 'PARSONS BLVD',
       '169 ST', 'JAMAICA 179 ST', 'COURT SQ', '21 ST', 'GREENPOINT AV',
       'NASSAU ST', 'BROADWAY', 'MYRTLE-WILLOUGH', 'BEDFORD-NOSTRAN',
       'CLASSON AV', '47-50 STS ROCK', '42 ST-BRYANT PK',
       "B'WAY-LAFAYETTE", '2 AV', 'EAST BROADWAY', 'YORK ST', 'BERGEN ST',
       'CARROLL ST', 'SMITH-9 ST', '4 AV-9 ST', '15 ST-PROSPECT',
       'DITMAS AV', 'AVENUE I', 'AVENUE N', 'AVENUE P', 'AVENUE X',
       'NEPTUNE AV', '57 ST', 'LEXINGTON AV/63', 'ROOSEVELT ISLND',
       '21 ST-QNSBRIDGE', 'JAMAICA VAN WK', 'SUTPHIN-ARCHER',
       'JAMAICA CENTER', 'ORCHARD BEACH', 'NEWARK HW BMEBE', 'HARRISON',
       'JOURNAL SQUARE', 'GROVE STREET', 'EXCHANGE PLACE',
       'PAVONIA/NEWPORT', 'CITY / BUS', 'CHRISTOPHER ST', '9TH STREET',
       '14TH STREET', 'TWENTY THIRD ST', 'THIRTY ST', 'LACKAWANNA',
       'THIRTY THIRD ST', 'NEWARK BM BW', 'NEWARK C', 'NEWARK HM HE',
       'PATH NEW WTC', 'SOUTH FERRY', 'WALL ST', 'FRANKLIN ST',
       'HOUSTON ST', '18 ST', '66 ST-LINCOLN', '116 ST-COLUMBIA',
       '137 ST CITY COL', '157 ST', '191 ST', '207 ST', '215 ST',
       'MARBLE HILL-225', '231 ST', '238 ST', 'V.CORTLANDT PK',
       'BOWLING GREEN', 'BROOKLYN BRIDGE', 'BLEECKER ST', 'ASTOR PL',
       '33 ST', 'GRD CNTRL-42 ST', '51 ST', '68ST-HUNTER CO', '110 ST',
       '138/GRAND CONC', '149/GRAND CONC', 'MT EDEN AV', '176 ST',
       'BURNSIDE AV', '183 ST', 'MOSHOLU PKWY', 'WOODLAWN',
       'CENTRAL PK N110', 'HARLEM 148 ST', '3 AV-149 ST', 'JACKSON AV',
       'INTERVALE AV', 'SIMPSON ST', 'FREEMAN ST', '174 ST',
       'WEST FARMS SQ', 'E 180 ST', 'BRONX PARK EAST', 'PELHAM PKWY',
       'ALLERTON AV', 'BURKE AV', 'GUN HILL RD', '219 ST', '225 ST',
       '233 ST', 'NEREID AV', 'WAKEFIELD/241', '3 AV 138 ST', 'BROOK AV',
       'CYPRESS AV', "E 143/ST MARY'S", 'E 149 ST', 'LONGWOOD AV',
       'HUNTS POINT AV', 'WHITLOCK AV', 'ELDER AV', 'MORISN AV/SNDVW',
       'ST LAWRENCE AV', 'PARKCHESTER', 'CASTLE HILL AV', 'ZEREGA AV',
       'WESTCHESTER SQ', 'MIDDLETOWN RD', 'BUHRE AV', 'PELHAM BAY PARK',
       '5 AVE', 'VERNON-JACKSON', 'HUNTERS PT AV', 'QUEENSBORO PLZ',
       '39 AV', '36 AV', '30 AV', 'ASTORIA BLVD', 'ASTORIA DITMARS',
       '33 ST-RAWSON ST', '40 ST LOWERY ST', '46 ST BLISS ST', '52 ST',
       '61 ST WOODSIDE', '69 ST', '74 ST-BROADWAY', '82 ST-JACKSON H',
       '90 ST-ELMHURST', 'JUNCTION BLVD', '103 ST-CORONA',
       'METS-WILLETS PT', 'FLUSHING-MAIN', '34 ST-HUDSON YD', 'CLARK ST',
       'HOYT ST', 'NEVINS ST', 'GRAND ARMY PLAZ', 'EASTN PKWY-MUSM',
       'KINGSTON AV', 'CROWN HTS-UTICA', 'SUTTER AV-RUTLD', 'SARATOGA AV',
       'JUNIUS ST', 'PENNSYLVANIA AV', 'NEW LOTS AV', 'PRESIDENT ST',
       'STERLING ST', 'WINTHROP ST', 'BEVERLY RD', 'NEWKIRK AV',
       'FLATBUSH AV-B.C', 'MORRIS PARK', 'BAYCHESTER AV',
       'EASTCHSTER/DYRE', 'ST. GEORGE', 'TOMPKINSVILLE', 'RIT-MANHATTAN',
       'RIT-ROOSEVELT'], dtype=object)

In [14]:
# displays all turnstiles for 59th st station at 12AM on 9/10/2016
df.loc[(df.STATION == '59 ST')&(df.TIME == '00:00:00')&(df.DATE == '09/10/2016')]

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,5817505,1971936
42,A002,R051,02-00-01,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,5344181,1172742
84,A002,R051,02-03-00,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,766935,2884286
126,A002,R051,02-03-01,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,5334462,8450233
168,A002,R051,02-03-02,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,5052167,6990552
210,A002,R051,02-03-03,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,4692803,5622073
252,A002,R051,02-03-04,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,5936731,3222966
294,A002,R051,02-03-05,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,9591682,1277009
336,A002,R051,02-03-06,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,7538640,475839
378,A002,R051,02-05-00,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,1310,0
420,A002,R051,02-05-01,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,0,705
462,A002,R051,02-06-00,59 ST,NQR456,BMT,09/10/2016,00:00:00,REGULAR,6628043,144684
22494,C021,R212,00-00-00,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,6583625,3581155
22536,C021,R212,00-00-01,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,6574128,4763456
22578,C021,R212,00-00-02,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,10166596,7679173
22620,C021,R212,00-00-03,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,11788664,13247318
22662,C022,R212,01-03-00,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,501590,129355
22704,C022,R212,01-05-00,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,262268,65536
22746,C022,R212,01-05-01,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,0,334
22788,C022,R212,01-06-00,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,4422829,3884336
22830,C022,R212,01-06-01,59 ST,NR,BMT,09/10/2016,00:00:00,REGULAR,9671407,3275067
149777,R244,R050,00-00-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,6061808,14303988
149819,R244,R050,00-00-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,8324936,8106246
149861,R244,R050,00-00-02,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,2756448,1708165
149903,R244,R050,00-00-03,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,34006,59779
149945,R244,R050,00-00-04,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,521199,2615841
149987,R244,R050,00-03-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,1429687,3590424
150029,R244,R050,00-03-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,739561,2071787
150071,R244,R050,00-03-02,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,2169590,4275397
150113,R244,R050,00-06-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,1288286,797144
150155,R244,R050,00-06-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,2340643,711627
150197,R244,R050,00-06-02,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,3403456,660591
150239,R244A,R050,01-00-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,3869771,14755931
150283,R244A,R050,01-00-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,4922645,2606620
150327,R244A,R050,01-00-02,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,16196468,5998383
150371,R244A,R050,01-00-03,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,6339365,1299008
150415,R244A,R050,01-00-04,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,2638294,467321
150459,R244A,R050,01-06-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,7197344,9094261
150503,R244A,R050,01-06-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,4310088,2603891
150547,R245,R051,00-00-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,14004406,2837746
150589,R245,R051,00-03-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,10381332,9598147
150631,R245,R051,00-03-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,5698366,13556083
150673,R245,R051,00-03-02,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,1040432236,737248138
150715,R245,R051,00-03-03,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,5773253,12058500
150757,R245,R051,00-05-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,10151541,9110209
150799,R245,R051,00-05-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,11854359,5158451
150841,R245,R051,00-05-02,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,6518118,1230720
150883,R245A,R051,01-00-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,9504621,3305391
150925,R245A,R051,01-00-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,10011431,5003637
150967,R245A,R051,01-00-02,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,5033273,7523710
151009,R245A,R051,01-00-03,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,1688728,3224643
151051,R245A,R051,01-06-00,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,2942598,3798239
151093,R245A,R051,01-06-01,59 ST,456NQR,IRT,09/10/2016,00:00:00,REGULAR,163348,2473928

In [43]:
# this confirms that any 'C/A' will only have one 'UNIT'  
u_units = df.groupby(['CA']).UNIT.nunique()
for x in u_units:
    if x!=1:
        print(x)
#  returns no results- x is always 1

In [41]:
# tells us any unit can have multiple CA's 
u_ca = df.groupby(['UNIT']).CA.nunique()
for y in u_ca:
    if y != 1:
        print(y)

3
2
2
3
4
3
5
2
2
3
2
3
3
3
2
2
4
6
4
4
3
3
3
2
4
4
3
2
3
2
3
2
2
2
3
2
2
2
2
2
4
2
2
3
2
2
2
2
2
2
2
2
2
4
3
3
2
2
2
2
2
3
2
2
2
3
2
4
2
2
2
2
2
2
3
3
3
2
2
2
2
2
2
2
5
3
2
3
2
2
5
2
2
2
2
4
2
2
2
2
2
2
2
2
2
2
5
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
3
2
2
2
2
4
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
4
2

In [50]:
# for each station, only 1 unique CA, UNIT pair exists
df.groupby(['STATION','CA']).UNIT.nunique()

STATION          CA
1 AV             H007     1
                 H008     1
103 ST           N037     1
                 R170     1
                 R252     1
103 ST-CORONA    R529     1
104 ST           J034     1
                 N137     1
110 ST           R253     1
                 R254     1
111 ST           J035     1
                 N138     1
                 N139     1
                 R530     1
116 ST           N029     1
                 N030     1
                 R256     1
                 R257     1
                 R302     1
                 R303     1
116 ST-COLUMBIA  R173     1
121 ST           J037     1
125 ST           N025     1
                 N026     1
                 R174     1
                 R258     1
                 R304     1
                 R305     1
135 ST           N022     1
                 N023     1
                         ..
VERNON-JACKSON   R504     1
                 R506     1
W 4 ST-WASH SQ   N080     1
                 N083     1
W 8 ST-AQUARIUM  G011     1
                 G015     1
WAKEFIELD/241    R336     1
WALL ST          R110     1
                 R111     1
                 R112     1
                 R112A    1
                 R203     1
                 R203A    1
                 R204     1
                 R204A    1
WEST FARMS SQ    R323     1
WESTCHESTER SQ   R420     1
WHITEHALL S-FRY  A058     1
                 A060     1
WHITLOCK AV      R413     1
WILSON AV        H032     1
WINTHROP ST      R637     1
WOODHAVEN BLVD   J031     1
                 J032     1
                 N329     1
                 N329A    1
WOODLAWN         R294     1
WORLD TRADE CTR  N094     1
YORK ST          N530     1
ZEREGA AV        R419     1
Name: UNIT, dtype: int64

In [13]:
df.groupby(['CA', 'UNIT', 'SCP', 'STATION', 'DATE', 'TIME'])

<pandas.core.groupby.DataFrameGroupBy object at 0x11629e208>